# 服务端口
server:
  port: 8003

# 环境设置：dev、test、prod
spring:
  application:
    # 服务名
    name: service-vod
  profiles:
    active: dev
  # 最大上传单个文件大小：默认1M
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI5tQM2N3HdnYFmtXtNLgn
      keysecret: LlgAx1iL2kBZEAG1cD2vOezNBYalLl