mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/liruicong/smsservice/mapper/xml/*.xml
server:
  port: 8005
spring:
  application:
    name: service-msm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Li19980503
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000