mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/liruicong/educenter/mapper/xml/*.xml
server:
  port: 8006
spring:
  application:
    name: service-ucenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Li19980503
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
wx:
  open:
    # 微信开放平台 appid
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url
    redirect_url: http://guli.shop/api/ucenter/wx/callback

