#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tQM2N3HdnYFmtXtNLgn
      keysecret: LlgAx1iL2kBZEAG1cD2vOezNBYalLl
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-ruicong